# Generated by Django 4.1.3 on 2022-11-27 04:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(choices=[], default='Choose', max_length=200)),
                ('user_id', models.UUIDField(default=uuid.UUID('cfef7f5b-7c8a-42ce-8c85-74babcd48eb8'), editable=False, unique=True)),
                ('username', models.CharField(max_length=500)),
                ('name', models.CharField(default=None, max_length=200)),
                ('surname', models.CharField(default=None, max_length=200)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('rank', models.CharField(choices=[('casual', 'Casual'), ('security', 'Security'), ('analyst', 'Analyst'), ('seniorAnalyst', 'Senior Analyst'), ('manager', 'Manager'), ('seniorManager', 'Senior Manager'), ('director', 'Director'), ('regionalDirector', 'Regional Director'), ('chiefFinancialDirector', 'Chief Financial Director')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('company_name', models.CharField(max_length=200)),
                ('username', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
